#include "utils.h" 

#ifndef __OLED_H
#define __OLED_H

#define OLED_I2C_ADDR 0x78

#define OLED_WIDTH_PX 128
#define OLED_HEIGHT_PX 32
#define OLED_BYTE_COUNT ((uint16_t)(OLED_WIDTH_PX*OLED_HEIGHT_PX)/8)
#define OLED_CHAR_WIDTH 6
#define OLED_CHAR_HEIGHT 8
#define OLED_SIZE_X ((uint8_t)(OLED_WIDTH_PX / OLED_CHAR_WIDTH))
#define OLED_SIZE_Y ((uint8_t)(OLED_HEIGHT_PX / OLED_CHAR_HEIGHT))
#define OLED_TOTAL_SIZE ((uint8_t)(OLED_SIZE_X * OLED_SIZE_Y))

#define OLED_EEPROM_FONT_ADDR			0x0000
#define OLED_CORE_EEPCONFIG_ADDR	0x0600
#define OLED_CORE_STRINGS_ADDR		0x0620
#define OLED_CORE_LOGO_ADDR				0x0A64
#define OLED_CUSTOM_DATA_ADDR			0x0C64
#define OLED_IMAGE_BUFF_SZ 64 //temp buff for speed increase, should be factor of oled W*H
#define OLED_STRING_BUFF_SZ 21 //another temp buff for speed increase
#define OLED_STRING_COUNT 32
#define OLED_FHASHLIGHT_KEYWORD (0xFFFF - OLED_BYTE_COUNT)
//extra chars
#define OLED_ECHAR_BATT_L 0x01
#define OLED_ECHAR_BATT_H 0x02
#define OLED_ECHAR_STR_EOL '_'
#define OLED_ECHAR_FIRST_IMG_ID 0x0B
#define OLED_ECHAR_LAST_IMG_ID 0x1F
#define OLED_ECHAR_PAGE_HEADER 0x09 //tab
#define OLED_ECHAR_RF_ONLINE 0x03

#define OLED_CHARGE_PUMP 0x8D
#define OLED_COLUMN_ADDR 0x21
#define OLED_COM_SCAN_DEC 0xC8
#define OLED_COM_SCAN_INC 0xC0
#define OLED_DISPLAY_ALL_ON 0xA5
#define OLED_DISPLAY_ALL_ON_RESUME 0xA4
#define OLED_DISPLAY_OFF 0xAE
#define OLED_DISPLAY_ON 0xAF
#define OLED_EXTERNAL_VCC 0x1
#define OLED_INVERT_DISPLAY 0xA7
#define OLED_MEMORY_MODE 0x20
#define OLED_NORMAL_DISPLAY 0xA6
#define OLED_PAGE_ADDR 0x22
#define OLED_SEG_REMAP 0xA0
#define OLED_SET_COMPINS 0xDA
#define OLED_SET_CONTRAST 0x81
#define OLED_SET_DISPLAY_CLOCK_DIV 0xD5
#define OLED_SET_DISPLAY_OFFSET 0xD3
#define OLED_SET_HIGH_COLUMN 0x10
#define OLED_SET_LOW_COLUMN 0x00
#define OLED_SET_MULTIPLEX 0xA8
#define OLED_SET_PRECHARGE 0xD9
#define OLED_SET_SEGMENT_REMAP 0xA1
#define OLED_SET_START_LINE 0x40
#define OLED_SET_VCOM_DETECT 0xDB
#define OLED_SWITCH_CAP_VCC 0x2

typedef enum {
	OLEDSTR_KEYBOARD_N1 = 0,
	OLEDSTR_KEYBOARD_N2,
	OLEDSTR_KEYBOARD_N3,
	OLEDSTR_KEYBOARD_N4,
	OLEDSTR_MAIN_MENU_CAP,
	OLEDSTR_MSGBOX_CAP,
	OLEDSTR_ABOUT_CAP,
	OLEDSTR_APPC_NOTES,
	OLEDSTR_APPC_CALC,
	OLEDSTR_APPC_CONFIG,
	OLEDSTR_APPC_TIMER,
	OLEDSTR_APPC_IR_REMOTE,
	OLEDSTR_APPC_SENSOR,
	OLEDSTR_LOW_BATT,
	OLEDSTR_MENU_NOTES,
	OLEDSTR_MENU_CALC,
	OLEDSTR_MENU_CONFIG,
	OLEDSTR_MENU_TIMER,
	OLEDSTR_MENU_IR_REMOTE,
	OLEDSTR_MENU_SENSOR,
	OLEDSTR_SOFT_VER,
	OLEDSTR_PCB_VER,
	OLEDSTR_CREATOR,
	OLEDSTR_APP_CALC_KEYS,
	OLEDSTR_APP_CONF_WELCOME,
	OLEDSTR_APP_CONF_VIBRO_EN,
	OLEDSTR_APP_CONF_EFFCT_EN,
	OLEDSTR_APP_CONF_CONTRAST,
	OLEDSTR_APP_CONF_AUTOSLP,
	OLEDSTR_APP_CONF_ROTATION,
	OLEDSTR_APP_CONF_RF_CH,
	OLEDSTR_APP_CONF_RF_ADDR,
	OLEDSTR_APP_CONF_RF_EN,
	OLEDSTR_APP_NOTES_STATIC,
	OLEDSTR_APP_NOTES_DYNAMIC,
	OLEDSTR_APP_NDMENU_NEXT_P,
	OLEDSTR_APP_NDMENU_PREV_P,
	OLEDSTR_APP_NDMENU_SEND,
	OLEDSTR_APP_NDMENU_ERASE,
	OLEDSTR_USB_MODE_STR1,
	OLEDSTR_USB_MODE_STR2,
	OLEDSTR_USB_MODE_STR3,
	OLEDSTR_USB_MODE_STR4,
	OLEDSTR_APP_SENOSOR_TEMP,
	OLEDSTR_APP_SENOSOR_HMDT,
	OLEDSTR_OPERATION_OK,
	OLEDSTR_RESERVED_1,
	OLEDSTR_RESERVED_2,
	OLEDSTR_RESERVED_3,
	OLEDSTR_RF_MSG_STR1,
	OLEDSTR_RF_MSG_STR2,
	OLEDSTR_RF_MSG_STR3,
	OLEDSTR_UNDEFINED
} OLED_STR_TypeDef;

#define KEYBOARD_STR_BEGIN OLEDSTR_KEYBOARD_N1
#define KEYBOARD_STR_END (OLEDSTR_KEYBOARD_N4 + 1)
#define MENU_STR_PG1_BEGIN OLEDSTR_MENU_NOTES
#define MENU_STR_PG1_END (OLEDSTR_MENU_CONFIG + 1)
#define MENU_STR_PG2_BEGIN OLEDSTR_MENU_TIMER
#define MENU_STR_PG2_END (OLEDSTR_MENU_SENSOR + 1)
#define MENU_PG_SIZE (MENU_STR_PG1_END - MENU_STR_PG1_BEGIN)
#define ABOUT_STR_BEGIN OLEDSTR_SOFT_VER
#define ABOUT_STR_END (OLEDSTR_CREATOR + 1)
#define CAPTION_STR_BEGIN OLEDSTR_MAIN_MENU_CAP
#define CAPTION_STR_END (OLEDSTR_APPC_SENSOR + 1)
#define CONFIG_STR_BEGIN OLEDSTR_APP_CONF_VIBRO_EN
#define NOTES_STR_BEGIN OLEDSTR_APP_NOTES_STATIC
#define NOTES_STR_END (OLEDSTR_APP_NOTES_DYNAMIC + 1)
#define NDMENU_STR_BEGIN OLEDSTR_APP_NDMENU_NEXT_P
#define NDMENU_STR_END (OLEDSTR_APP_NDMENU_ERASE + 1)
#define USBMODE_STR_BEGIN OLEDSTR_USB_MODE_STR1
#define USBMODE_STR_END (OLEDSTR_USB_MODE_STR4 + 1)
#define SENSOR_STR_BEGIN OLEDSTR_APP_SENOSOR_TEMP
#define SENSOR_STR_END (OLEDSTR_APP_SENOSOR_HMDT + 1)
#define RF_MSG_STR_BEGIN OLEDSTR_RF_MSG_STR1
#define RF_MSG_STR_END (OLEDSTR_RF_MSG_STR3 + 1)

typedef enum {
	OLEDCT_LOW = 0,
	OLEDCT_MEDIUM = 94,
	OLEDCT_HIGH = 188,
	OLEDCT_INVALD
} OLED_CONTRAST_TypeDef;

#define IS_OLED_BUFF_X_OK(x) \
	((x) < (OLED_SIZE_X)) 
#define IS_OLED_BUFF_Y_OK(y) \
	((y) < (OLED_SIZE_Y)) 
#define IS_OLED_STR_ID_OK(id) \
	((id) < (OLED_STRING_COUNT)) 
	
struct oled_struct {
	bool redraw_flag, rotation;
	uint16_t img_adddr;
	uint8_t inv_area_sz;
	struct pos2d_struct inv_pos;
};


void OLED_Init(OLED_CONTRAST_TypeDef lvl, bool rot);
void OLED_Command(uint8_t cmd);
uint8_t OLED_ReadByte(uint8_t addr);
void OLED_Clear(void);
void OLED_Update(void);
void OLED_Redraw(void);
void OLED_SetChar(uint8_t char_code, uint8_t x, uint8_t y);
void OLED_DrawImage(uint16_t addr);
void OLED_StartLine(void);
uint8_t OLED_GetChar(uint8_t x, uint8_t y);
void OLED_PrintString(OLED_STR_TypeDef id, uint8_t y);
void OLED_InverseArea(struct pos2d_struct *pos_ptr, uint8_t size);
void OLED_PrintStringList(uint8_t start_y, OLED_STR_TypeDef str_begin, OLED_STR_TypeDef str_end);
void OLED_PrintNumber(int32_t number, uint8_t reverse_x, uint8_t y);

#endif /* __OLED_H */